name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # Set up Docker Buildx (for better multi-platform support)

      - name: Cache Docker layers
        uses: actions/cache@v2 # Cache Docker layers for faster builds
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t supportdeskback.azurecr.io/my-jenkins-image:latest .

      - name: Push Docker image to Azure Container Registry
        run: |
          docker push supportdeskback.azurecr.io/my-jenkins-image:latest
